# Generated by Django 5.2.5 on 2025-09-04 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_queueuser_is_verified_queueuser_otp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('request_type', models.CharField(choices=[('general', 'General'), ('late', 'Running Late'), ('forward', 'Request Forward in Queue'), ('help', 'Need Assistance')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
                ('handled_note', models.TextField(blank=True)),
                ('queue_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='app1.queueuser')),
            ],
        ),
    ]
