# Generated by Django 5.2.5 on 2025-09-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_userrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueuser',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='queueuser',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
