# Generated by Django 5.2.5 on 2025-09-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_queueuser_is_available_queueuser_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='Staff', max_length=50),
        ),
    ]
